# github action to deploy api

name: Deploy API

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GerenciadorClinicas  
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x  

      - name: Restore dependencies
        run: dotnet restore GerenciadorClinicas.sln

      - name: Build
        run: dotnet build GerenciadorClinicas.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test GerenciadorClinicas.sln --no-build --verbosity normal